  devdoc[m
  devdoc-daria[m
  devdoc-intro2[m
  devdoc-requirements[m
  devdoc-seq-diag[m
  devdoc-use-cases[m
  develop[m
* [32mdevelop-settings[m
  diagrams[m
  example[m
  master[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/backdev[m
  [31mremotes/origin/dev-registration[m
  [31mremotes/origin/devdoc[m
  [31mremotes/origin/devdoc-intro2[m
  [31mremotes/origin/devdoc-requirements[m
  [31mremotes/origin/devdoc-seq-diag[m
  [31mremotes/origin/devdoc-seq-diag-2[m
  [31mremotes/origin/devdoc-use-cases[m
  [31mremotes/origin/develop[m
  [31mremotes/origin/develop-settings[m
  [31mremotes/origin/develop-userhome[m
  [31mremotes/origin/develop_react_refactor[m
  [31mremotes/origin/diagrams[m
  [31mremotes/origin/documentation-introduction[m
  [31mremotes/origin/example[m
  [31mremotes/origin/frontdev[m
  [31mremotes/origin/master[m
